agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from agency.views import (
    NewspaperListView,
    TopicListView,
    topic_newspapers,
    NewspaperDetailView,
    RedactorListView,
    redactor_newspapers,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    register,
    RedactorUpdateView,
    TopicCreateView,
    RedactorDeleteView,
)


urlpatterns = [
    path("registration/", register, name="register"),
    path("", NewspaperListView.as_view(), name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/<int:pk>/", topic_newspapers, name="topic-newspapers"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactors/<int:pk>/", redactor_newspapers, name="redactor-newspapers"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "newspaper/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "agency"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

agency/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from newspaper_agency import settings
import re


class Topic(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="topics/", null=True, blank=True)

    def get_absolute_url(self):
        return reverse("agency:topic-newspapers", kwargs={"pk": self.id})

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.PositiveIntegerField(default=0)
    avatar = models.ImageField(upload_to="redactors/", null=True, blank=True)

    def get_absolute_url(self):
        return reverse("agency:redactor-newspapers", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.get_full_name()}"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    publication_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(
        to=Topic, on_delete=models.CASCADE, related_name="newspapers"
    )
    publishers = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL, related_name="newspapers"
    )
    image = models.ImageField(upload_to="newspapers/", null=True, blank=True)

    @property
    def get_short_content(self):
        short_content = re.sub(r"<[^>]*>", "", self.content)[:150]
        return (
            short_content + "..." if len(self.content) > 150 else self.content
        )

    @property
    def get_short_publishers(self):
        publishers = self.publishers.all()
        short_list = ", ".join(
            f"<a href='{publisher.get_absolute_url()}'>{publisher}</a>"
            for publisher in publishers[:2]
        )
        if len(publishers) > 2:
            short_list += "..."
        return short_list

    @property
    def get_full_publishers(self):
        return ", ".join(
            f"<a href='{publisher.get_absolute_url()}'>{publisher}</a>"
            for publisher in self.publishers.all()
        )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-publication_date"]

agency/forms.py
from crispy_forms.bootstrap import FieldWithButtons, StrictButton
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django_summernote.widgets import SummernoteWidget

from agency.models import Newspaper, Redactor


class SearchFormMixin(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            FieldWithButtons(
                f"{self.obj}",
                StrictButton("Search", type="submit"),
                input_size="input-group-sm",
            )
        )


class RedactorRegistrationForm(UserCreationForm):
    class Meta:
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class RedactorForm(UserCreationForm):
    class Meta:
        model = Redactor
        fields = [
            "first_name",
            "last_name",
            "years_of_experience",
            "username",
            "password1",
            "password2",
            "avatar",
        ]


class RedactorUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = [
            "first_name",
            "last_name",
            "years_of_experience",
            "avatar",
        ]


class NewspaperForm(forms.ModelForm):
    content = forms.CharField(widget=SummernoteWidget)
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class TopicSearchForm(SearchFormMixin, forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )
    obj = "name"


class NewspaperSearchForm(SearchFormMixin, forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )
    obj = "title"


class RedactorSearchForm(SearchFormMixin, forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )
    obj = "username"

agency/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from agency.forms import (
    NewspaperForm,
    NewspaperSearchForm,
    TopicSearchForm,
    RedactorSearchForm,
    RedactorRegistrationForm,
    RedactorForm, RedactorUpdateForm,
)
from agency.models import Newspaper, Topic, Redactor


def register(request):
    if request.method == "POST":
        registration_form = RedactorRegistrationForm(
            request.POST, request.FILES
        )
        if registration_form.is_valid():
            user = registration_form.save()
            login(request, user)
            return redirect("/")
    else:
        if request.user.is_authenticated:
            return redirect("/")
        registration_form = RedactorRegistrationForm()
    return render(
        request, "registration/register.html", {"form": registration_form}
    )


class NewspaperAccessMixin:
    def get(self, request, *args, **kwargs):
        newspaper = self.get_object()
        if request.user not in newspaper.publishers.all():
            return redirect("agency:index")
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        newspaper = self.get_object()
        if request.user not in newspaper.publishers.all():
            return redirect("agency:index")
        return super().post(request, *args, **kwargs)


class RedactorAccessMixin:
    def get(self, request, *args, **kwargs):
        user = self.get_object()
        if request.user != user:
            return redirect("agency:index")
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.get_object()
        if request.user != user:
            return redirect("agency:index")
        return super().post(request, *args, **kwargs)


class NewspaperListView(generic.ListView):
    model = Newspaper
    template_name = "agency/index.html"
    paginate_by = 6
    queryset = Newspaper.objects.prefetch_related("publishers")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_form"] = NewspaperSearchForm(initial={"title": title})
        return context

    def get_queryset(self):
        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                title__istartswith=form.cleaned_data["title"]
            )
        return self.queryset


class TopicListView(generic.ListView):
    model = Topic
    queryset = Topic.objects.all()
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TopicSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__istartswith=form.cleaned_data["name"]
            )
        return self.queryset


def topic_newspapers(request: HttpRequest, pk) -> HttpResponse:
    newspaper_list = Newspaper.objects.filter(topic_id=pk)
    form = NewspaperSearchForm(request.GET)
    search_query = request.GET.get("title")
    topic = get_object_or_404(Topic, pk=pk)
    if search_query:
        newspaper_list = newspaper_list.filter(title__icontains=search_query)
    page_number = request.GET.get("page")
    paginator = Paginator(newspaper_list, 6)
    try:
        newspaper_list = paginator.page(page_number)
    except PageNotAnInteger:
        newspaper_list = paginator.page(1)
    except EmptyPage:
        newspaper_list = paginator.page(paginator.num_pages)
    context = {
        "newspaper_list": newspaper_list,
        "page_obj": newspaper_list,
        "is_paginated": newspaper_list.has_other_pages,
        "search_form": form,
        "topic": topic,
    }
    return render(request, "agency/topic_newspapers.html", context)


class NewspaperDetailView(generic.DetailView):
    model = Newspaper
    queryset = Newspaper.objects.select_related("topic").prefetch_related("publishers")


class RedactorListView(generic.ListView):
    model = Redactor
    queryset = Redactor.objects.all()
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = RedactorSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__istartswith=form.cleaned_data["username"]
            )
        return self.queryset


def redactor_newspapers(request: HttpRequest, pk) -> HttpResponse:
    redactor = get_object_or_404(Redactor, pk=pk)
    newspaper_list = Newspaper.objects.filter(
        publishers=redactor
    ).select_related("topic").prefetch_related("publishers")
    topic_obj = newspaper_list.values("topic").annotate(Count("topic")).order_by("-topic__count").first()
    if topic_obj:
        topic_pk = topic_obj["topic"]
        topic = Topic.objects.get(pk=topic_pk)
    else:
        topic = None
    form = NewspaperSearchForm(request.GET)
    search_query = request.GET.get("title")

    if search_query:
        newspaper_list = newspaper_list.filter(title__icontains=search_query)

    paginator = Paginator(newspaper_list, 6)
    page_number = request.GET.get("page")

    try:
        newspaper_list = paginator.page(page_number)
    except PageNotAnInteger:
        newspaper_list = paginator.page(1)
    except EmptyPage:
        newspaper_list = paginator.page(paginator.num_pages)

    context = {
        "newspaper_list": newspaper_list,
        "page_obj": newspaper_list,
        "is_paginated": newspaper_list.has_other_pages,
        "search_form": form,
        "redactor": redactor,
        "page_number": page_number,
        "topic": topic
    }
    return render(request, "agency/redactor_newspapers.html", context)


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    success_url = reverse_lazy("agency:index")
    form_class = NewspaperForm


class NewspaperUpdateView(
    LoginRequiredMixin, NewspaperAccessMixin, generic.UpdateView
):
    model = Newspaper
    success_url = reverse_lazy("agency:index")
    form_class = NewspaperForm


class NewspaperDeleteView(
    LoginRequiredMixin, NewspaperAccessMixin, generic.DeleteView
):
    model = Newspaper
    success_url = reverse_lazy("agency:index")


class RedactorUpdateView(
    LoginRequiredMixin, RedactorAccessMixin, generic.UpdateView
):
    model = Redactor
    success_url = reverse_lazy("agency:index")
    form_class = RedactorUpdateForm


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("agency:index")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("agency:index")

templates/agency/index.html
{% extends "base.html" %}
{% block content %}
    {% include "includes/search_line.html" %}
    {% include "includes/newspapers.html" %}
{% endblock %}

{% block footer %}
    {% include "includes/footer.html" %}
{% endblock %}

templates/agency/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6 text-center">
      <h2>Are you sure that you want to delete "{{ newspaper }}"</h2>
      <form action="" method="post">
                {% csrf_token %}
        <div style="margin-top: 100px; padding-bottom: 150px;">
    <div class="col mt-5">
              <button type="button" onclick="history.back()" class="btn btn-secondary" style="float: left; min-width: 150px; ">Cancel</button>
            </div>
            <div class="col">
              <button type="submit" class="btn btn-danger" style="float: right; min-width: 150px; margin-left: 150px;">Confirm</button>
            </div>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/agency/newspaper_detail.html
{% extends "base.html" %}

{% block header %}
<header class="masthead" style="height: 700px; background-image: url('{% if newspaper.image %}{{ newspaper.image.url }}{% else %}/static/assets/img/default-bg.jpg{% endif %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    {% if user in newspaper.publishers.all %}
                    <span class="meta" style="float: right">
                        <a href="{% url "agency:newspaper-update" pk=newspaper.id %}">Edit</a>
                        <br><br>
                        <a href="{% url "agency:newspaper-delete" pk=newspaper.id %}">Delete</a>
                    </span>
                    {% endif %}
                    <h1>{{ newspaper }}</h1>
                    <h2 class="subheading">topic: <a href="{% url "agency:topic-newspapers" pk=newspaper.topic.id %}" style="color: white">{{ newspaper.topic }}</a></h2>
                    <span class="meta">
                        Posted by: {{ newspaper.get_full_publishers | safe }}
                        <br><br>
                        Publication date: {{ newspaper.publication_date }}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {{ newspaper.content | safe }}
            </div>
        </div>
    </div>
</article>
{% endblock %}

templates/agency/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
<div class="container px-4 px-lg-5 mb-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
  <h1 class="mt-5 mb-4 text-center">{{ object|yesno:"Update,Create" }} newspaper</h1>
    <br>
      <form action="" method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
          <div class="col mt-5" style="width: 720px">
            <button type="button" onclick="history.back()" class="btn btn-secondary" style="float: left">Cancel</button>
            <button type="submit" class="btn btn-primary" style="float: right">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/agency/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6 text-center">
      <h2>Are you sure that you want to delete your profile?</h2>
      <form action="" method="post">
        {% csrf_token %}
        <div style="margin-top: 100px; padding-bottom: 150px;">
    <div class="col mt-5">
              <button type="button" onclick="history.back()" class="btn btn-secondary" style="float: left; min-width: 150px; ">Cancel</button>
            </div>
            <div class="col">
              <button type="submit" class="btn btn-danger" style="float: right; min-width: 150px; margin-left: 150px;">Confirm</button>
            </div>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/agency/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container px-4 px-lg-5 mb-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <h1 class="mt-5 mb-4 text-center">Update redactor</h1>
      <br>
      <form action="" method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
          <div class="col mt-5" style="width: 720px">
              <button type="button" onclick="history.back()" class="btn btn-secondary" style="float:left">Cancel</button>
              <button type="submit" class="btn btn-primary" style="float:right">Submit</button>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/agency/redactor_list.html
{% extends "base.html" %}

{% block content %}
    {% include "includes/search_line.html" %}
    <div class="container py-5">
        <div class="row mb-4 mb-lg-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h2 class="fw-bold">Our Redactors</h2>
            </div>
        </div>
        <div class="container">
            <div class="row text-center">
                {% if redactor_list %}
                    {% for redactor in redactor_list %}
                        <div class="col-xl-3 col-sm-6 mb-5">
                            <a href="{% url 'agency:redactor-newspapers' pk=redactor.id %}">
                                <div class="bg-white rounded shadow-sm py-5 px-4">
                                    <img class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm"
                                         {% if redactor.avatar %}
                                             src="{{ redactor.avatar.url }}" alt="{{ redactor.get_full_name }}"
                                         {% else %}
                                             src="https://st3.depositphotos.com/13159112/17145/v/450/depositphotos_171453724-stock-illustration-default-avatar-profile-icon-grey.jpg"
                                         {% endif %}
                                         alt="{{ redactor.get_full_name }}" width="100">
                                    <h5 class="mb-0">{{ redactor.get_full_name }}</h5>
                                    <span class="small text-muted">Experience: {{ redactor.years_of_experience }} year{{ redactor.years_of_experience|pluralize }}</span>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="col-md-8 col-xl-6 text-center mx-auto">
                        <p class="fw-bold">No redactors</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/agency/redactor_newspapers.html
{% extends "base.html" %}
{% load static %}
{% block header %}
<header class="masthead" style="height: 450px; background-image: url('{% static 'assets/img/default-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    {% if user.id == redactor.id %}
                        <span class="meta" style="float: right">
                            <a href="{% url "agency:redactor-update" pk=redactor.id %}" style="color: #ffffffff">Edit</a>
                            <br><br>
                            <a href="{% url "agency:redactor-delete" pk=redactor.id %}" style="color: #ffffffff">Delete</a>
                        </span>
                    {% endif %}
                    <h1 style="font-size: 50px">{{ redactor }}</h1>
                    <span class="subheading">
                        Experience: {{ redactor.years_of_experience }} year{{ redactor.years_of_experience|pluralize }}
                        <br><br>Articles published: {{ redactor.newspapers.count }}
                      {% if topic %}
                      <br><br>
                      Favourite topic: {{ topic }}
                      {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
    {% include "includes/search_line.html" %}
    {% include "includes/newspapers.html" %}
{% endblock %}

templates/agency/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container px-4 px-lg-5 mb-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <h1 class="mt-5 mb-4 text-center">{{ object|yesno:"Update,Create" }} topic</h1>
      <br>
      <form action="" method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
            <div class="col mt-5" style="width: 720px">
              <button type="button" onclick="history.back()" class="btn btn-secondary" style="float: left">Cancel</button>
              <button type="submit" class="btn btn-primary" style="float:right">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/agency/topic_list.html
{% extends "base.html" %}
{% block content %}
    {% include "includes/search_line.html" %}
    <div class="container">
        <div class="heading text-center">
            <h2>Topics</h2>
            <i><a href="{% url "agency:topic-create" %}" style="color: #000000; padding-left: 1200px">Create</a></i>
        </div>
        <br>
        {% if topic_list %}
        <div class="row">
            {% for topic in topic_list %}
            <div class="col-4 py-3 mx-auto col-xl-4 col-lg-6 col-md-6 col-sm-10" style="min-width: 280px; min-height: 280px;">
                <div class="card" style="width: 100%; height: 100%;">
                    <a href="{% url "agency:topic-newspapers" pk=topic.id %}">
                        <img class="img-fluid card-img-top" style="height: 250px; object-fit: cover"
                             {% if topic.image %}
                             src="{{ topic.image.url}}"
                             {% else %}
                             src="https://www.poynter.org/wp-content/themes/elumine/assets/images/default-img.jpg"
                             {% endif %}
                        />
                    </a>
                    <div class="card-body">
                        <h5>{{ topic.name}}</h5>
                        <p>Articles: {{ topic.newspapers.count }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <p class="fw-bold">No topics</p>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/agency/topic_newspapers.html
{% extends "base.html" %}

{% block header %}
<header class="masthead" style="height: 450px; background-image: url('{% if topic.image %}{{ topic.image.url }}{% else %}/static/assets/img/default-bg.jpg{% endif %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1 style="font-size: 50px">{{ topic.name }}</h1>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
    {% include "includes/search_line.html" %}
    {% include "includes/newspapers.html" %}
{% endblock %}