agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from agency.views import (
    NewspaperListView,
    TopicListView,
    topic_newspapers,
    NewspaperDetailView,
    RedactorListView,
    redactor_newspapers,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    register,
    RedactorUpdateView,
    TopicCreateView,
    RedactorDeleteView,
)


urlpatterns = [
    path("registration/", register, name="register"),
    path("", NewspaperListView.as_view(), name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/<int:pk>/", topic_newspapers, name="topic-newspapers"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path(
        "redactors/<int:pk>/", redactor_newspapers, name="redactor-newspapers"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "newspaper/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail",
    ),
    path(
        "newspaper/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "agency"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

agency/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from newspaper_agency import settings
import re


class Topic(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="topics/", null=True, blank=True)

    def get_absolute_url(self):
        return reverse("agency:topic-newspapers", kwargs={"pk": self.id})

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.PositiveIntegerField(default=0)
    avatar = models.ImageField(upload_to="redactors/", null=True, blank=True)

    def get_absolute_url(self):
        return reverse("agency:redactor-newspapers", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.get_full_name()}"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    publication_date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(
        to=Topic, on_delete=models.CASCADE, related_name="newspapers"
    )
    publishers = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL, related_name="newspapers"
    )
    image = models.ImageField(upload_to="newspapers/", null=True, blank=True)

    @property
    def get_short_content(self):
        short_content = re.sub(r"<[^>]*>", "", self.content)[:150]
        return (
            short_content + "..." if len(self.content) > 150 else self.content
        )

    @property
    def get_short_publishers(self):
        publishers = self.publishers.all()
        short_list = ", ".join(
            f"<a href='{publisher.get_absolute_url()}'>{publisher}</a>"
            for publisher in publishers[:2]
        )
        if len(publishers) > 2:
            short_list += "..."
        return short_list

    @property
    def get_full_publishers(self):
        return ", ".join(
            f"<a href='{publisher.get_absolute_url()}'>{publisher}</a>"
            for publisher in self.publishers.all()
        )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-publication_date"]

templates/includes/footer.html
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                <div class="small text-center text-muted fst-italic">Copyright &copy; Kyiv Chronicle 2023</div>
            </div>
        </div>
    </div>
</footer>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        {% if user.is_authenticated  %}
    <a class="navbar-brand" href="{% url "agency:redactor-newspapers" pk=user.id %}">{{ user.get_full_name }}</a>
  {% endif %}

        <div class="navbar-collapse">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "agency:topic-list" %}">Topics</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "agency:redactor-list" %}">Redactors</a></li>
                {% if user.is_authenticated %}
                  <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "agency:newspaper-create" %}">Write</a></li>
                  <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "logout" %}">Logout</a></li>
                  {% else %}
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "login" %}">Login</a></li>
              {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/includes/newspapers.html
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
              <div class="col-md-8 col-xl-6 text-center mx-auto">
                {% if page_obj.has_previous %}
              <h2 class="fw-bold">Articles</h2>
                {% else %}
                  <h2 class="fw-bold">Last Articles</h2>
                {% endif %}
              </div>
     <div class="col-md-10 col-lg-8 col-xl-7">
                {% if newspaper_list %}
                  {% for newspaper in newspaper_list %}
                    <div class="post-preview">
                        <a href="/newspaper/{{ newspaper.id }}">
                            <h2 class="post-title">{{ newspaper.title }}</h2>
                            <h3 class="post-subtitle">{{ newspaper.get_short_content | striptags }}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            {{ newspaper.get_short_publishers | safe}}
                          on {{ newspaper.publication_date}}
                        </p>
                      <p>Topic: <a href="{{ newspaper.topic.get_absolute_url }}" style="text-decoration: none">{{ newspaper.topic }}</a></p>
                    </div>
                    <hr class="my-4" />
                  {% endfor %}
                {% else %}
                  <div class="row gx-4 gx-lg-5 justify-content-center">
              <div class="col-md-8 col-xl-6 text-center mx-auto">
              <p class="fw-bold"> No artiles</p>
                {% endif %}
                </div>
            </div>
        </div>
            </div>
            </div>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
<div class="container" >
  <div class="row justify-space-between py-2">
    <div class="col-lg-4 mx-auto">
      <ul class="pagination pagination-primary m-4">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}" aria-label="Previous">
            <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
          </a>
        </li>
        {% endif %}

        {% for page_number in page_obj.paginator.page_range %}
        <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
          <a class="page-link" href="?{% query_transform request page=page_number %}">{{ page_number }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}" aria-label="Next">
            <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endif %}

templates/includes/search_line.html
{% load crispy_forms_tags %}

<form class="search-form" style="margin-left: 300px; margin-right: 300px; padding-left: 50px; padding-right: 50px;">
    {% csrf_token %}
    {% crispy search_form %}
    <div class="input-group">

    </div>
</form>
<br>